"""Make profile_picture and id_document nullable

Revision ID: 413910717b71
Revises: 16288c62c0d5
Create Date: 2025-07-30 04:09:42.877540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '413910717b71'
down_revision = '16288c62c0d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.alter_column('profile_picture',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('id_document',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.alter_column('id_document',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('profile_picture',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###
