"""Add date_needed to Job

Revision ID: 6b8931e90588
Revises: bae9927b6989
Create Date: 2025-08-01 20:36:44.444953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b8931e90588'
down_revision = 'bae9927b6989'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('dob',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('dob',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###
