"""ensure job zone and date_needed

Revision ID: 77862e69de5d
Revises: 72de0aa1ef99
Create Date: 2025-08-15 16:22:22.422369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77862e69de5d'
down_revision = '72de0aa1ef99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zone', sa.String(length=64), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('zone')

    # ### end Alembic commands ###
