"""Rename recurring_frequency to recurrence_pattern in Job

Revision ID: 77ce070f41c6
Revises: 82a384221d6f
Create Date: 2025-08-19 18:44:26.703246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77ce070f41c6'
down_revision = '82a384221d6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurrence_pattern', sa.String(length=50), nullable=True))
        batch_op.drop_column('recurring_frequency')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurring_frequency', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('recurrence_pattern')

    # ### end Alembic commands ###
