"""Add date_needed to Job model

Revision ID: 7bb1f56184cc
Revises: 413910717b71
Create Date: 2025-07-30 04:39:37.877835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bb1f56184cc'
down_revision = '413910717b71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_needed', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('date_needed')

    # ### end Alembic commands ###
