"""Add dob to User

Revision ID: bae9927b6989
Revises: 7bb1f56184cc
Create Date: 2025-08-01 19:52:28.712776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bae9927b6989'
down_revision = '7bb1f56184cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dob', sa.Date(), nullable=True))

    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('dob')

    # ### end Alembic commands ###
