"""Add payment_amount to Job

Revision ID: f8aec8f9b361
Revises: 77862e69de5d
Create Date: 2025-08-15 16:56:04.356957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8aec8f9b361'
down_revision = '77862e69de5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_amount', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('payment_amount')

    # ### end Alembic commands ###
